name: "Release new artifacts"

on:
  release:
    types:
      - created
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  REGISTRY: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com
  IMAGE: blockchain-taiko-gethx
  DOCKERFILE: Dockerfile.debank

jobs:
  build-artifacts:
    strategy:
      matrix:
        arch: [amd64]
    runs-on: [self-hosted, "${{ matrix.arch }}"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.RELEASE_MANAGER_APP_ID }}
          private_key: ${{ secrets.RELEASE_MANAGER_APP_SECRET }}

      - name: Set env
        run: |
          echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build image and push to ECR
        uses:  docker/build-push-action@v5
        with:
          file: ${{ env.DOCKERFILE }}
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ matrix.arch }}-${{ env.REVISION }}
          build-args: ACCESS_TOKEN=${{ steps.generate-token.outputs.token }}
          provenance: false